Test/Fix: add test,mockData, and migrations files
*context.js abstraction of jest beforeAll and
afterAll functionality for easy reuse
*dbEntry2.integration.test.js : to enable
remove file path from jest ignore path in
package.json after local db setup or test
fail
* migrations: migrations used my node-pg-migrate
to pgAdmin
Fix:
*babelrc remove "@babel/preset-env" because of
error: SyntaxError: /Users/justingillespie
/Github/cs/projects/Allok8/server/pool.js:
 Missing class properties transform
 ** resolved error, additional info in
 file comments
*cmdStrController fix condition logic
*eslintrc.json : fix thrown linter errors over
jest methods

Test: verified non-breaking by automated tests
and manual testing